name: Deploy to GitHub Pages

on:
  push:
    # TODO! Update back to master once we're done.
    branches: [ deployment ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Clean previous build artifacts
        run: |
          rm -rf docs/.astro
          rm -rf docs/dist
          rm -rf docs/src/content/docs/api

      - name: Install, build, and upload
        uses: withastro/action@v5
        with:
          path: ./docs
          build-cmd: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
